FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_EVOLUTION_API_URL
ARG VITE_EVOLUTION_API_KEY
ARG VITE_DEFAULT_NEW_USER_PASSWORD=Imobi@1234
ARG VITE_ENABLE_ANON_LOGIN=false
ARG VITE_FEATURE_RT_DEBUG_LEADS=false
ARG VITE_FEATURE_RT_TRANSFER_FIX=false

ENV VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
ENV VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
ENV VITE_EVOLUTION_API_URL=${VITE_EVOLUTION_API_URL}
ENV VITE_EVOLUTION_API_KEY=${VITE_EVOLUTION_API_KEY}
ENV VITE_DEFAULT_NEW_USER_PASSWORD=${VITE_DEFAULT_NEW_USER_PASSWORD}
ENV VITE_ENABLE_ANON_LOGIN=${VITE_ENABLE_ANON_LOGIN}
ENV VITE_FEATURE_RT_DEBUG_LEADS=${VITE_FEATURE_RT_DEBUG_LEADS}
ENV VITE_FEATURE_RT_TRANSFER_FIX=${VITE_FEATURE_RT_TRANSFER_FIX}

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
